#!/usr/bin/env bash
# Script that creates a PID file and handles signals
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
